In [10]:
import pandas as pd

In [11]:
pd.read_excel("data.xlsx")

     Name     School  Marks
0  Shubham       olx     34
1     Jack       bba     43
2     Alex       wps     24
3     Hary       aps     87
4   Bhadva  mcSchool     75
5   Akash         bc     98
6  Jasmine  mzSchool     12

In [12]:
df =  pd.read_json("data.json")

In [13]:
df

      name  age      city
0   Shreya   25  New York
1  atharva   70  Thailand

In [ ]:
df = pd.read_csv("https://gist.github.com/curran/a08a1080b88344b0c8a7#file-iris-csv")